import type { BuiltinTemplate, TemplateBlock } from "./builtinTemplates";

/**
 * More of the templates Formkit ships with: feedback, HR, events, marketing,
 * sales and education. Same shape as the first thirteen (builtinTemplates.ts),
 * kept apart only to keep that file readable. The marketing site's copy for
 * each lives in `src/content/templates.ts`, matched by slug.
 */

const page = (pageName: string): TemplateBlock => ({ kind: "pagebreak", pageName });
const f = (type: string, title: string, extra: Record<string, unknown> = {}): TemplateBlock =>
  ({ kind: "field", type, title, ...extra }) as TemplateBlock;

export const MORE_TEMPLATES: BuiltinTemplate[] = [
  {
    slug: "customer-satisfaction-survey",
    name: "Customer Satisfaction Survey",
    topic: "Business",
    icon: "star",
    accent: "var(--yellow-200)",
    blurb: "A short CSAT survey: how satisfied, what worked, what to fix.",
    audience: "Anyone who sells or serves",
    welcome: { title: "How did we do?", message: "Five questions, under two minutes.", button: "Start" },
    thanks: { title: "Thank you", message: "We read every answer, and it shapes what we do next." },
    blocks: [
      f("scale", "How satisfied are you with us overall?", { scaleMin: 1, scaleMax: 5, required: true }),
      f("multi-choice", "What went well?", {
        options: ["Speed", "Quality", "Communication", "Price", "The people", "Something else"],
      }),
      f("long-text", "What should we do better?"),
      f("yes-no", "Can we follow up with you about your answers?"),
      f("email", "Your email", { help: "Only if you said yes above" }),
    ],
  },
  {
    slug: "nps-survey",
    name: "NPS Survey",
    topic: "Business",
    icon: "gauge",
    accent: "var(--blue-200)",
    blurb: "Net Promoter Score in two questions, plus the reason behind the number.",
    audience: "Product and customer teams",
    welcome: { title: "One quick question", message: "Two questions, thirty seconds." },
    thanks: { title: "Thank you", message: "Your answer goes straight to the team." },
    blocks: [
      f("scale", "How likely are you to recommend us to a friend or colleague?", {
        scaleMin: 0,
        scaleMax: 10,
        required: true,
      }),
      f("long-text", "What is the main reason for your score?"),
      f("single-choice", "How long have you been a customer?", {
        options: ["Less than 3 months", "3 to 12 months", "1 to 3 years", "More than 3 years"],
      }),
    ],
  },
  {
    slug: "event-feedback",
    name: "Event Feedback",
    topic: "Events",
    icon: "party-popper",
    accent: "var(--red-200)",
    blurb: "What people thought of the day, the talks and the venue, while it is fresh.",
    audience: "Event organisers",
    welcome: { title: "How was the event?", message: "Six questions, about two minutes." },
    thanks: { title: "Thank you for coming", message: "Your feedback shapes the next one." },
    blocks: [
      f("scale", "Overall, how would you rate the event?", { scaleMin: 1, scaleMax: 5, required: true }),
      f("single-choice", "Which session was most useful?", {
        options: ["The opening keynote", "The workshops", "The panel", "Meeting people", "None stood out"],
      }),
      f("scale", "How was the venue?", { scaleMin: 1, scaleMax: 5 }),
      f("yes-no", "Would you come again?"),
      f("long-text", "What should we change next time?"),
      f("email", "Email, if you would like to hear about the next one"),
    ],
  },
  {
    slug: "employee-feedback",
    name: "Employee Feedback",
    topic: "HR",
    icon: "users",
    accent: "var(--mint-200)",
    blurb: "An engagement pulse: workload, support, growth and what to change.",
    audience: "HR and team leads",
    welcome: {
      title: "How is work going?",
      message: "Seven questions. Answers are read by HR and shared only as totals.",
      button: "Start",
    },
    thanks: { title: "Thank you", message: "We share what we learn, and what we will do about it, within a month." },
    blocks: [
      f("scale", "How happy are you at work right now?", { scaleMin: 1, scaleMax: 5, required: true }),
      f("scale", "How manageable is your workload?", { scaleMin: 1, scaleMax: 5 }),
      f("scale", "How supported do you feel by your manager?", { scaleMin: 1, scaleMax: 5 }),
      f("yes-no", "Can you see how you could grow here?"),
      f("long-text", "What is one thing we should keep doing?"),
      f("long-text", "What is one thing we should change?"),
      f("dropdown", "Which team are you in?", {
        options: ["Product", "Engineering", "Design", "Sales", "Operations", "Other"],
      }),
    ],
  },
  {
    slug: "exit-interview",
    name: "Exit Interview",
    topic: "HR",
    icon: "log-out",
    accent: "var(--neutral-150)",
    blurb: "Why people leave, asked kindly, so the next person stays longer.",
    audience: "HR teams",
    welcome: { title: "Before you go", message: "Eight questions. Honest answers help the people who stay." },
    thanks: { title: "Thank you, and good luck", message: "We are grateful for your time here." },
    blocks: [
      f("name", "Your name"),
      f("dropdown", "What is the main reason you are leaving?", {
        required: true,
        options: ["A new opportunity", "Pay", "Growth", "Management", "Workload", "Relocation", "Personal reasons", "Other"],
      }),
      f("scale", "How would you rate your time here overall?", { scaleMin: 1, scaleMax: 5 }),
      f("long-text", "What did we do well?"),
      f("long-text", "What could we have done to keep you?"),
      f("yes-no", "Would you recommend working here to a friend?"),
      f("yes-no", "Would you consider coming back one day?"),
      f("long-text", "Anything else you would like us to know?"),
    ],
  },
  {
    slug: "employee-onboarding",
    name: "New Hire Onboarding",
    topic: "HR",
    icon: "user-round",
    accent: "var(--blue-300)",
    blurb: "Details, equipment and preferences from a new starter before day one.",
    audience: "HR and office managers",
    welcome: { title: "Welcome aboard", message: "Three short pages so everything is ready for your first day." },
    thanks: { title: "All set", message: "We will send your first-day plan a week before you start." },
    blocks: [
      page("About you"),
      f("name", "Full name", { required: true }),
      f("email", "Personal email", { required: true }),
      f("phone", "Phone number"),
      f("address", "Home address", { required: true }),
      f("date", "Date of birth"),
      page("Your setup"),
      f("single-choice", "Which laptop would you like?", { options: ["Mac", "Windows", "No preference"] }),
      f("single-choice", "Where will you mostly work?", { options: ["In the office", "At home", "A mix"] }),
      f("short-text", "T-shirt size, for the welcome pack"),
      page("Just in case"),
      f("name", "Emergency contact", { required: true }),
      f("phone", "Emergency contact's phone", { required: true }),
      f("long-text", "Anything we should know to make work easier for you?", {
        help: "Access needs, dietary needs, anything at all",
      }),
    ],
  },
  {
    slug: "time-off-request",
    name: "Time Off Request",
    topic: "HR",
    icon: "calendar",
    accent: "var(--yellow-200)",
    blurb: "Dates, type of leave and cover, routed to the right manager.",
    audience: "Teams of any size",
    welcome: { title: "Request time off", message: "Six questions. Your manager hears straight away." },
    thanks: { title: "Request sent", message: "Your manager will approve or reply within two working days." },
    blocks: [
      f("name", "Your name", { required: true }),
      f("email", "Your work email", { required: true }),
      f("single-choice", "Type of leave", {
        required: true,
        options: ["Holiday", "Sick leave", "Parental leave", "Unpaid leave", "Other"],
      }),
      f("date", "First day off", { required: true }),
      f("date", "Last day off", { required: true }),
      f("short-text", "Who is covering for you?"),
      f("long-text", "Anything your manager should know?"),
    ],
  },
  {
    slug: "volunteer-signup",
    name: "Volunteer Sign-up",
    topic: "Events",
    icon: "heart",
    accent: "var(--red-200)",
    blurb: "Who can help, when, and doing what.",
    audience: "Charities, clubs and events",
    welcome: { title: "Thank you for helping", message: "Seven questions, about two minutes." },
    thanks: { title: "You are on the list", message: "We will be in touch with your shifts a week before." },
    blocks: [
      f("name", "Full name", { required: true }),
      f("email", "Email", { required: true }),
      f("phone", "Phone number"),
      f("multi-choice", "When can you help?", {
        required: true,
        options: ["Weekday mornings", "Weekday afternoons", "Evenings", "Weekends"],
      }),
      f("multi-choice", "What would you like to do?", {
        options: ["Welcome and registration", "Setting up", "Food and drink", "Clearing up", "Anything that helps"],
      }),
      f("yes-no", "Have you volunteered with us before?"),
      f("long-text", "Anything we should know?", { help: "Access needs, skills, or times you cannot do" }),
    ],
  },
  {
    slug: "workshop-registration",
    name: "Workshop Registration",
    topic: "Events",
    icon: "calendar-check",
    accent: "var(--blue-200)",
    blurb: "Places, experience level and payment for a paid workshop.",
    audience: "Trainers, studios and teachers",
    welcome: { title: "Book your place", message: "Five questions, then payment if the workshop is paid." },
    thanks: { title: "Your place is booked", message: "The joining details are on their way to your inbox." },
    blocks: [
      f("name", "Full name", { required: true }),
      f("email", "Email", { required: true }),
      f("dropdown", "Which date?", { required: true, options: ["Saturday 12 October", "Saturday 9 November", "Saturday 7 December"] }),
      f("single-choice", "Your experience level", { options: ["Complete beginner", "Some experience", "Confident"] }),
      f("number", "How many places?", { required: true }),
      f("long-text", "What do you hope to get out of it?"),
    ],
  },
  {
    slug: "webinar-registration",
    name: "Webinar Registration",
    topic: "Marketing",
    icon: "mic",
    accent: "var(--mint-200)",
    blurb: "Sign-ups for a live session, with the question people want answered.",
    audience: "Marketing teams",
    welcome: { title: "Save your seat", message: "Four questions. The link arrives by email." },
    thanks: { title: "You are registered", message: "We will email the link, and a reminder an hour before." },
    blocks: [
      f("name", "Full name", { required: true }),
      f("email", "Work email", { required: true }),
      f("company", "Company"),
      f("dropdown", "Your role", { options: ["Founder", "Marketing", "Sales", "Product", "Operations", "Other"] }),
      f("long-text", "What would you like us to cover?"),
    ],
  },
  {
    slug: "newsletter-signup",
    name: "Newsletter Sign-up",
    topic: "Marketing",
    icon: "mail",
    accent: "var(--blue-300)",
    blurb: "An email, a name, and what people want to hear about.",
    audience: "Writers, shops and brands",
    welcome: { title: "Join the newsletter", message: "Three questions, ten seconds." },
    thanks: { title: "You are in", message: "The next issue lands in your inbox. Unsubscribe any time." },
    blocks: [
      f("email", "Email", { required: true }),
      f("short-text", "First name"),
      f("multi-choice", "What would you like to hear about?", {
        options: ["New products", "Guides and how-tos", "Events", "Offers"],
      }),
    ],
  },
  {
    slug: "waitlist",
    name: "Product Waitlist",
    topic: "Marketing",
    icon: "rocket",
    accent: "var(--yellow-200)",
    blurb: "Early-access sign-ups that tell you who is keenest.",
    audience: "Founders and product teams",
    welcome: { title: "Get early access", message: "Five questions. We let people in a few at a time." },
    thanks: { title: "You are on the list", message: "We will email you as soon as your spot opens." },
    blocks: [
      f("email", "Email", { required: true }),
      f("name", "Name"),
      f("company", "Company"),
      f("single-choice", "How soon would you use it?", {
        options: ["Straight away", "In the next few months", "Just curious"],
      }),
      f("long-text", "What problem would it solve for you?"),
    ],
  },
  {
    slug: "testimonial-request",
    name: "Testimonial Request",
    topic: "Marketing",
    icon: "quote",
    accent: "var(--neutral-150)",
    blurb: "Collect quotes from happy clients, with permission to use them.",
    audience: "Freelancers, agencies and shops",
    welcome: { title: "Would you say a few words?", message: "Five questions, two minutes. Thank you." },
    thanks: { title: "Thank you so much", message: "We will send you the finished quote before it goes live." },
    blocks: [
      f("name", "Your name", { required: true }),
      f("short-text", "Your role and company"),
      f("long-text", "What was it like working with us?", { required: true }),
      f("file", "A photo of you, if you would like one shown", { accept: [".jpg", ".jpeg", ".png"] }),
      f("single-choice", "Can we use your words on our website?", {
        required: true,
        options: ["Yes, with my name", "Yes, without my name", "No, just for you"],
      }),
    ],
  },
  {
    slug: "quote-request",
    name: "Quote Request",
    topic: "Business",
    icon: "receipt",
    accent: "var(--mint-200)",
    blurb: "What someone needs, and enough detail to price it the first time.",
    audience: "Service businesses",
    welcome: { title: "Get a quote", message: "Seven questions. We reply with a price, not a sales call." },
    thanks: { title: "Request received", message: "We will send your quote within one working day." },
    blocks: [
      f("name", "Your name", { required: true }),
      f("email", "Email", { required: true }),
      f("phone", "Phone number"),
      f("multi-choice", "What do you need?", {
        required: true,
        options: ["Design", "Build", "Maintenance", "Consulting", "Something else"],
      }),
      f("long-text", "Tell us about the job", { required: true }),
      f("dropdown", "Budget", { options: ["Under $1,000", "$1,000 to $5,000", "$5,000 to $20,000", "Over $20,000"] }),
      f("date", "When do you need it by?"),
    ],
  },
  {
    slug: "booking-request",
    name: "Appointment Booking",
    topic: "Business",
    icon: "calendar-check",
    accent: "var(--blue-200)",
    blurb: "A service, a preferred time and the details to confirm it.",
    audience: "Salons, clinics, coaches and consultants",
    welcome: { title: "Book an appointment", message: "Six questions. We confirm by email." },
    thanks: { title: "Request received", message: "We will confirm your time by email, usually within a few hours." },
    blocks: [
      f("name", "Full name", { required: true }),
      f("email", "Email", { required: true }),
      f("phone", "Phone number", { required: true }),
      f("dropdown", "Which service?", { required: true, options: ["Consultation", "Standard session", "Extended session", "Follow-up"] }),
      f("date", "Preferred date", { required: true }),
      f("single-choice", "Preferred time", { options: ["Morning", "Afternoon", "Evening"] }),
      f("long-text", "Anything we should know beforehand?"),
    ],
  },
  {
    slug: "bug-report",
    name: "Bug Report",
    topic: "Business",
    icon: "bug",
    accent: "var(--red-200)",
    blurb: "What broke, where, and how to make it happen again.",
    audience: "Software teams",
    welcome: { title: "Report a bug", message: "Seven questions. The more detail, the faster the fix." },
    thanks: { title: "Thanks, we are on it", message: "We will email you when it is fixed." },
    blocks: [
      f("email", "Your email", { required: true }),
      f("short-text", "What went wrong, in one line?", { required: true }),
      f("long-text", "Steps to make it happen again", { required: true, placeholder: "1. Go to…\n2. Click…\n3. See…" }),
      f("long-text", "What did you expect to happen?"),
      f("single-choice", "How bad is it?", {
        options: ["It blocks my work", "It is annoying", "It is cosmetic"],
      }),
      f("dropdown", "Browser or device", { options: ["Chrome", "Safari", "Firefox", "Edge", "iPhone", "Android", "Other"] }),
      f("file", "Screenshot or recording"),
    ],
  },
  {
    slug: "partnership-inquiry",
    name: "Partnership Inquiry",
    topic: "Business",
    icon: "handshake",
    accent: "var(--yellow-200)",
    blurb: "Who they are, what they propose, and whether it is worth a call.",
    audience: "Founders and partnership teams",
    welcome: { title: "Let's work together", message: "Six questions, about three minutes." },
    thanks: { title: "Thank you", message: "We read every proposal and reply within a week." },
    blocks: [
      f("name", "Your name", { required: true }),
      f("email", "Work email", { required: true }),
      f("company", "Company", { required: true }),
      f("url", "Website"),
      f("single-choice", "What kind of partnership?", {
        options: ["Reseller", "Integration", "Co-marketing", "Affiliate", "Something else"],
      }),
      f("long-text", "What do you have in mind?", { required: true }),
    ],
  },
  {
    slug: "creative-brief",
    name: "Creative Brief",
    topic: "Agency",
    icon: "palette",
    accent: "var(--blue-300)",
    blurb: "Objective, audience, message and deliverables, agreed before work starts.",
    audience: "Agencies and in-house teams",
    welcome: { title: "The brief", message: "Three pages. The clearer the brief, the better the work." },
    thanks: { title: "Brief received", message: "We will come back with questions, or a plan, within two days." },
    blocks: [
      page("The goal"),
      f("short-text", "Project name", { required: true }),
      f("long-text", "What are we trying to achieve?", { required: true }),
      f("long-text", "Who is it for?", { required: true }),
      page("The message"),
      f("short-text", "The one thing people should remember"),
      f("multi-choice", "Tone", { options: ["Warm", "Playful", "Confident", "Serious", "Premium", "Plain-spoken"] }),
      f("file", "Brand guidelines or references"),
      page("Practicalities"),
      f("multi-choice", "Deliverables", { options: ["Social posts", "Video", "Print", "Web pages", "Email", "Other"] }),
      f("date", "Deadline", { required: true }),
      f("dropdown", "Budget", { options: ["Under $5,000", "$5,000 to $20,000", "$20,000 to $50,000", "Over $50,000"] }),
    ],
  },
  {
    slug: "client-feedback",
    name: "Project Feedback",
    topic: "Agency",
    icon: "message-square",
    accent: "var(--mint-200)",
    blurb: "How a finished project went, and whether they would work with you again.",
    audience: "Studios, freelancers and agencies",
    welcome: { title: "How did the project go?", message: "Six questions, about three minutes." },
    thanks: { title: "Thank you", message: "It was a pleasure working with you." },
    blocks: [
      f("scale", "How happy are you with the result?", { scaleMin: 1, scaleMax: 5, required: true }),
      f("scale", "How was working with us day to day?", { scaleMin: 1, scaleMax: 5 }),
      f("long-text", "What stood out?"),
      f("long-text", "What could we have done better?"),
      f("yes-no", "Would you work with us again?"),
      f("yes-no", "Can we quote you on our website?"),
    ],
  },
  {
    slug: "photography-booking",
    name: "Photography Booking",
    topic: "Personal",
    icon: "camera",
    accent: "var(--neutral-150)",
    blurb: "Shoot type, date, location and the shots that matter.",
    audience: "Photographers and videographers",
    welcome: { title: "Book a shoot", message: "Seven questions. I will reply with availability and a quote." },
    thanks: { title: "Thank you", message: "I will be in touch within two days to confirm." },
    blocks: [
      f("name", "Your name", { required: true }),
      f("email", "Email", { required: true }),
      f("single-choice", "What kind of shoot?", {
        required: true,
        options: ["Wedding", "Portrait", "Family", "Event", "Product", "Brand"],
      }),
      f("date", "Date of the shoot", { required: true }),
      f("short-text", "Location"),
      f("number", "How many hours, roughly?"),
      f("long-text", "Any shots you really want?"),
    ],
  },
  {
    slug: "quiz",
    name: "Knowledge Check Quiz",
    topic: "Education",
    icon: "clipboard-check",
    accent: "var(--blue-200)",
    blurb: "A short marked quiz. Turn on quiz mode to add answers, a timer and a pass mark.",
    audience: "Teachers, trainers and HR",
    welcome: { title: "Knowledge check", message: "Six questions. Take your time and do your best.", button: "Begin" },
    thanks: { title: "Thanks for taking the quiz", message: "Your results are on their way." },
    blocks: [
      f("name", "Your name", { required: true }),
      f("email", "Your email", { required: true }),
      f("single-choice", "Which of these is a primary colour?", { required: true, options: ["Green", "Blue", "Purple", "Orange"] }),
      f("single-choice", "How many sides does a hexagon have?", { required: true, options: ["Five", "Six", "Seven", "Eight"] }),
      f("multi-choice", "Which of these are mammals?", { required: true, options: ["Whale", "Shark", "Bat", "Penguin"] }),
      f("short-text", "What is the capital of France?", { required: true }),
      f("long-text", "In a sentence, why do leaves change colour in autumn?"),
    ],
  },
  {
    slug: "course-evaluation",
    name: "Course Evaluation",
    topic: "Education",
    icon: "graduation-cap",
    accent: "var(--mint-200)",
    blurb: "What students thought of the content, the teaching and the pace.",
    audience: "Schools, universities and trainers",
    welcome: { title: "How was the course?", message: "Seven questions. Answers are anonymous." },
    thanks: { title: "Thank you", message: "Your answers help us improve the course for the next group." },
    blocks: [
      f("dropdown", "Which course did you take?", { required: true, options: ["Course A", "Course B", "Course C"] }),
      f("scale", "Overall, how would you rate the course?", { scaleMin: 1, scaleMax: 5, required: true }),
      f("scale", "How clear was the teaching?", { scaleMin: 1, scaleMax: 5 }),
      f("single-choice", "How was the pace?", { options: ["Too slow", "About right", "Too fast"] }),
      f("long-text", "What was the most useful part?"),
      f("long-text", "What would you change?"),
      f("yes-no", "Would you recommend this course?"),
    ],
  },
  {
    slug: "course-registration",
    name: "Course Registration",
    topic: "Education",
    icon: "graduation-cap",
    accent: "var(--yellow-200)",
    blurb: "Student details, course choice and anything the teacher should know.",
    audience: "Schools, academies and tutors",
    welcome: { title: "Register for a course", message: "Two short pages, about three minutes." },
    thanks: { title: "You are registered", message: "We will email your timetable and joining details." },
    blocks: [
      page("The student"),
      f("name", "Student's full name", { required: true }),
      f("email", "Email", { required: true }),
      f("phone", "Phone number"),
      f("date", "Date of birth"),
      page("The course"),
      f("dropdown", "Which course?", { required: true, options: ["Beginners", "Intermediate", "Advanced"] }),
      f("single-choice", "Preferred schedule", { options: ["Weekday mornings", "Weekday evenings", "Weekends"] }),
      f("long-text", "Anything the teacher should know?", { help: "Learning needs, previous experience" }),
    ],
  },
  {
    slug: "course-application",
    name: "Program Application",
    topic: "Education",
    icon: "clipboard-check",
    accent: "var(--blue-300)",
    blurb: "Applications for a course, bootcamp or scholarship, with a statement and documents.",
    audience: "Schools, bootcamps and fellowships",
    welcome: { title: "Apply", message: "Three pages, about ten minutes. You can save and come back." },
    thanks: { title: "Application received", message: "We will let you know the outcome within three weeks." },
    blocks: [
      page("About you"),
      f("name", "Full name", { required: true }),
      f("email", "Email", { required: true }),
      f("short-text", "Where are you based?"),
      page("Your background"),
      f("dropdown", "Highest level of study", {
        options: ["Secondary school", "College", "Undergraduate degree", "Postgraduate degree", "Other"],
      }),
      f("long-text", "Tell us about relevant experience", { required: true }),
      f("url", "Portfolio or LinkedIn"),
      page("Your application"),
      f("long-text", "Why do you want to join?", { required: true }),
      f("file", "CV or supporting document", { accept: [".pdf", ".doc", ".docx"] }),
    ],
  },
];

/** Where the new ones sit in the library, after the first thirteen. */
export const MORE_ORDER = MORE_TEMPLATES.map((t) => t.slug);
