/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by scripts/convex-codegen.mjs - do not edit by hand.
 */

import { anyApi } from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 */
export const api = anyApi;
export const internal = anyApi;
