/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by scripts/convex-codegen.mjs — do not edit by hand.
 */

import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";
import type * as auth from "../auth.js";
import type * as email from "../email.js";
import type * as emails_authCode from "../emails/authCode.js";
import type * as http from "../http.js";
import type * as model_identity from "../model/identity.js";
import type * as users from "../users.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "auth": typeof auth,
  "email": typeof email,
  "emails/authCode": typeof emails_authCode,
  "http": typeof http,
  "model/identity": typeof model_identity,
  "users": typeof users,
}>;
export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;
