/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by scripts/convex-codegen.mjs - do not edit by hand.
 */

import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";
import type * as admin from "../admin.js";
import type * as adminCompanies from "../adminCompanies.js";
import type * as adminReports from "../adminReports.js";
import type * as adminTally from "../adminTally.js";
import type * as ai from "../ai.js";
import type * as aiLogic from "../aiLogic.js";
import type * as aiReply from "../aiReply.js";
import type * as aiUsage from "../aiUsage.js";
import type * as analytics from "../analytics.js";
import type * as approvals from "../approvals.js";
import type * as auth from "../auth.js";
import type * as billing from "../billing.js";
import type * as blocks from "../blocks.js";
import type * as collaborators from "../collaborators.js";
import type * as comments from "../comments.js";
import type * as companies from "../companies.js";
import type * as connections from "../connections.js";
import type * as controls from "../controls.js";
import type * as credits from "../credits.js";
import type * as crons from "../crons.js";
import type * as digests from "../digests.js";
import type * as domains from "../domains.js";
import type * as email from "../email.js";
import type * as emailDomains from "../emailDomains.js";
import type * as emails_authCode from "../emails/authCode.js";
import type * as emails_kit from "../emails/kit.js";
import type * as emails_response from "../emails/response.js";
import type * as exports from "../exports.js";
import type * as flags from "../flags.js";
import type * as forms from "../forms.js";
import type * as handles from "../handles.js";
import type * as helpSignals from "../helpSignals.js";
import type * as http from "../http.js";
import type * as inbox from "../inbox.js";
import type * as insights from "../insights.js";
import type * as logic from "../logic.js";
import type * as model_access from "../model/access.js";
import type * as model_aiForms from "../model/aiForms.js";
import type * as model_aiIntent from "../model/aiIntent.js";
import type * as model_aiMeter from "../model/aiMeter.js";
import type * as model_aiPrices from "../model/aiPrices.js";
import type * as model_aiReply from "../model/aiReply.js";
import type * as model_apiKeys from "../model/apiKeys.js";
import type * as model_builtinTemplates from "../model/builtinTemplates.js";
import type * as model_calc from "../model/calc.js";
import type * as model_contacts from "../model/contacts.js";
import type * as model_exportSheet from "../model/exportSheet.js";
import type * as model_flags from "../model/flags.js";
import type * as model_forms from "../model/forms.js";
import type * as model_gemini from "../model/gemini.js";
import type * as model_grants from "../model/grants.js";
import type * as model_handles from "../model/handles.js";
import type * as model_identity from "../model/identity.js";
import type * as model_inbox from "../model/inbox.js";
import type * as model_logicCopy from "../model/logicCopy.js";
import type * as model_logicEval from "../model/logicEval.js";
import type * as model_logicOps from "../model/logicOps.js";
import type * as model_money from "../model/money.js";
import type * as model_moreTemplates from "../model/moreTemplates.js";
import type * as model_places from "../model/places.js";
import type * as model_plans from "../model/plans.js";
import type * as model_quiz from "../model/quiz.js";
import type * as model_responseCounts from "../model/responseCounts.js";
import type * as model_responseSearch from "../model/responseSearch.js";
import type * as model_scan from "../model/scan.js";
import type * as model_security from "../model/security.js";
import type * as model_sheet from "../model/sheet.js";
import type * as model_spaces from "../model/spaces.js";
import type * as model_standing from "../model/standing.js";
import type * as model_team from "../model/team.js";
import type * as model_themePresets from "../model/themePresets.js";
import type * as model_totp from "../model/totp.js";
import type * as model_voice from "../model/voice.js";
import type * as notifications from "../notifications.js";
import type * as payments from "../payments.js";
import type * as presence from "../presence.js";
import type * as publicForm from "../publicForm.js";
import type * as quiz from "../quiz.js";
import type * as responses from "../responses.js";
import type * as restApi from "../restApi.js";
import type * as revenue from "../revenue.js";
import type * as security from "../security.js";
import type * as spaces from "../spaces.js";
import type * as sso from "../sso.js";
import type * as support from "../support.js";
import type * as team from "../team.js";
import type * as templates from "../templates.js";
import type * as users from "../users.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "admin": typeof admin,
  "adminCompanies": typeof adminCompanies,
  "adminReports": typeof adminReports,
  "adminTally": typeof adminTally,
  "ai": typeof ai,
  "aiLogic": typeof aiLogic,
  "aiReply": typeof aiReply,
  "aiUsage": typeof aiUsage,
  "analytics": typeof analytics,
  "approvals": typeof approvals,
  "auth": typeof auth,
  "billing": typeof billing,
  "blocks": typeof blocks,
  "collaborators": typeof collaborators,
  "comments": typeof comments,
  "companies": typeof companies,
  "connections": typeof connections,
  "controls": typeof controls,
  "credits": typeof credits,
  "crons": typeof crons,
  "digests": typeof digests,
  "domains": typeof domains,
  "email": typeof email,
  "emailDomains": typeof emailDomains,
  "emails/authCode": typeof emails_authCode,
  "emails/kit": typeof emails_kit,
  "emails/response": typeof emails_response,
  "exports": typeof exports,
  "flags": typeof flags,
  "forms": typeof forms,
  "handles": typeof handles,
  "helpSignals": typeof helpSignals,
  "http": typeof http,
  "inbox": typeof inbox,
  "insights": typeof insights,
  "logic": typeof logic,
  "model/access": typeof model_access,
  "model/aiForms": typeof model_aiForms,
  "model/aiIntent": typeof model_aiIntent,
  "model/aiMeter": typeof model_aiMeter,
  "model/aiPrices": typeof model_aiPrices,
  "model/aiReply": typeof model_aiReply,
  "model/apiKeys": typeof model_apiKeys,
  "model/builtinTemplates": typeof model_builtinTemplates,
  "model/calc": typeof model_calc,
  "model/contacts": typeof model_contacts,
  "model/exportSheet": typeof model_exportSheet,
  "model/flags": typeof model_flags,
  "model/forms": typeof model_forms,
  "model/gemini": typeof model_gemini,
  "model/grants": typeof model_grants,
  "model/handles": typeof model_handles,
  "model/identity": typeof model_identity,
  "model/inbox": typeof model_inbox,
  "model/logicCopy": typeof model_logicCopy,
  "model/logicEval": typeof model_logicEval,
  "model/logicOps": typeof model_logicOps,
  "model/money": typeof model_money,
  "model/moreTemplates": typeof model_moreTemplates,
  "model/places": typeof model_places,
  "model/plans": typeof model_plans,
  "model/quiz": typeof model_quiz,
  "model/responseCounts": typeof model_responseCounts,
  "model/responseSearch": typeof model_responseSearch,
  "model/scan": typeof model_scan,
  "model/security": typeof model_security,
  "model/sheet": typeof model_sheet,
  "model/spaces": typeof model_spaces,
  "model/standing": typeof model_standing,
  "model/team": typeof model_team,
  "model/themePresets": typeof model_themePresets,
  "model/totp": typeof model_totp,
  "model/voice": typeof model_voice,
  "notifications": typeof notifications,
  "payments": typeof payments,
  "presence": typeof presence,
  "publicForm": typeof publicForm,
  "quiz": typeof quiz,
  "responses": typeof responses,
  "restApi": typeof restApi,
  "revenue": typeof revenue,
  "security": typeof security,
  "spaces": typeof spaces,
  "sso": typeof sso,
  "support": typeof support,
  "team": typeof team,
  "templates": typeof templates,
  "users": typeof users,
}>;
export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;
