/**
 * Offline Convex codegen.
 *
 * `npx convex codegen` contacts api.convex.dev before it will write anything,
 * and that host is blocked by this environment's egress policy. This script
 * writes the same `convex/_generated` files from the local module tree so the
 * app typechecks and builds without a network round-trip.
 *
 * It is a stand-in, not a replacement: run `npx convex dev` on a machine that
 * can reach Convex to push the schema and functions for real. The output shape
 * matches convex's own templates (see
 * node_modules/convex/dist/cjs/cli/codegen_templates/).
 *
 *   node scripts/convex-codegen.mjs
 */
import { mkdirSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const convexDir = join(root, "convex");
const outDir = join(convexDir, "_generated");

/** Files Convex does not treat as function modules. */
const SKIP = new Set(["schema.ts", "auth.config.ts", "convex.config.ts", "tsconfig.json"]);

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    if (entry === "_generated" || entry.startsWith(".")) continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      out.push(...walk(full));
      continue;
    }
    if (!/\.(ts|js|tsx|jsx)$/.test(entry)) continue;
    if (/\.d\.ts$/.test(entry)) continue;
    if (SKIP.has(relative(convexDir, full))) continue;
    out.push(relative(convexDir, full).replace(/\\/g, "/"));
  }
  return out.sort();
}

const importPath = (p) => p.replace(/\.[^.]+$/, "");

function moduleIdentifier(p) {
  let id = importPath(p).replace(/\//g, "_").replace(/-/g, "_");
  if (["fullApi", "api", "internal", "components"].includes(id)) id += "_";
  return id;
}

const header = (what) => `/* eslint-disable */
/**
 * ${what}
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by scripts/convex-codegen.mjs — do not edit by hand.
 */
`;

const modules = walk(convexDir);

mkdirSync(outDir, { recursive: true });

writeFileSync(
  join(outDir, "api.d.ts"),
  `${header("Generated `api` utility.")}
import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";
${modules.map((m) => `import type * as ${moduleIdentifier(m)} from "../${importPath(m)}.js";`).join("\n")}

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * \`\`\`js
 * const myFunctionReference = api.myModule.myFunction;
 * \`\`\`
 */
declare const fullApi: ApiFromModules<{
${modules.map((m) => `  "${importPath(m)}": typeof ${moduleIdentifier(m)},`).join("\n")}
}>;
export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;
`,
);

writeFileSync(
  join(outDir, "api.js"),
  `${header("Generated `api` utility.")}
import { anyApi } from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 */
export const api = anyApi;
export const internal = anyApi;
`,
);

writeFileSync(
  join(outDir, "dataModel.d.ts"),
  `${header("Generated data model types.")}
import type {
  DataModelFromSchemaDefinition,
  DocumentByName,
  TableNamesInDataModel,
  SystemTableNames,
} from "convex/server";
import type { GenericId } from "convex/values";
import schema from "../schema.js";

/** The names of all of your Convex tables. */
export type TableNames = TableNamesInDataModel<DataModel>;

/** The type of a document stored in Convex. */
export type Doc<TableName extends TableNames> = DocumentByName<DataModel, TableName>;

/** An identifier for a document in Convex. */
export type Id<TableName extends TableNames | SystemTableNames> = GenericId<TableName>;

/** A type describing your Convex data model. */
export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
`,
);

writeFileSync(
  join(outDir, "server.d.ts"),
  `${header("Generated utilities for implementing server-side Convex query and mutation functions.")}
import {
  ActionBuilder,
  HttpActionBuilder,
  MutationBuilder,
  QueryBuilder,
  GenericActionCtx,
  GenericMutationCtx,
  GenericQueryCtx,
  GenericDatabaseReader,
  GenericDatabaseWriter,
} from "convex/server";
import type { DataModel } from "./dataModel.js";

export declare const query: QueryBuilder<DataModel, "public">;
export declare const internalQuery: QueryBuilder<DataModel, "internal">;
export declare const mutation: MutationBuilder<DataModel, "public">;
export declare const internalMutation: MutationBuilder<DataModel, "internal">;
export declare const action: ActionBuilder<DataModel, "public">;
export declare const internalAction: ActionBuilder<DataModel, "internal">;
export declare const httpAction: HttpActionBuilder;

export declare const env: Record<string, string | undefined>;

export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type ActionCtx = GenericActionCtx<DataModel>;
export type DatabaseReader = GenericDatabaseReader<DataModel>;
export type DatabaseWriter = GenericDatabaseWriter<DataModel>;
`,
);

writeFileSync(
  join(outDir, "server.js"),
  `${header("Generated utilities for implementing server-side Convex query and mutation functions.")}
import {
  actionGeneric,
  httpActionGeneric,
  queryGeneric,
  mutationGeneric,
  internalActionGeneric,
  internalMutationGeneric,
  internalQueryGeneric,
} from "convex/server";

export const query = queryGeneric;
export const internalQuery = internalQueryGeneric;
export const mutation = mutationGeneric;
export const internalMutation = internalMutationGeneric;
export const action = actionGeneric;
export const internalAction = internalActionGeneric;
export const httpAction = httpActionGeneric;

export const env = process.env;
`,
);

console.log(`convex/_generated written for ${modules.length} modules:`);
for (const m of modules) console.log(`  ${importPath(m)}`);
